import type { TenantContext } from '../../../../../packages/contracts/src/index.js';
import { withTenantTransaction, type SqlDatabase, type SqlTransaction } from '../../../../../packages/database/src/index.js';
import { randomToken, isSafeOpaqueToken } from '../../../../../packages/crypto/src/tokens.js';
import { sha256Hex } from '../../../../../packages/crypto/src/hash.js';
import { TicBankIdProvider, verifyTicWebhook, parseAndHashTicWebhookEnvelope, assertTicWebhookBinding } from '../../../../../packages/provider-adapters/src/tic-bankid.js';
import { ResendEmailProvider } from '../../../../../packages/provider-adapters/src/email.js';
import type { PublicSigningRepository, ProviderWebhookRepository, PublicVerificationRepository, PublicSigningInvitationView, PublicBankIdSessionView } from '../../ports.js';
import type { ProductionInfrastructure } from './infrastructure.js';
import { createEvidenceZip, verifyEvidenceZip } from '../../../../../packages/evidence/src/zip.js';

const SYSTEM_ACTOR_ID='00000000-0000-0000-0000-000000000000';

export interface PublicRepositorySet {
  readonly publicSigning: PublicSigningRepository;
  readonly providerWebhooks: ProviderWebhookRepository;
  readonly publicVerification: PublicVerificationRepository;
}

export function createPublicRepositories(
  database: SqlDatabase,
  infrastructure: ProductionInfrastructure,
  configuration: Readonly<Record<string,string|undefined>>,
): PublicRepositorySet {
  const ticEnabled=configuration.TIC_BANKID_ENABLED?.toLowerCase()==='true';
  const tic=ticEnabled ? new TicBankIdProvider({
    baseUrl:required(configuration,'TIC_BASE_URL'),apiKey:required(configuration,'TIC_API_KEY'),
    callbackUrl:required(configuration,'TIC_CALLBACK_URL'),webhookUrl:required(configuration,'TIC_WEBHOOK_URL'),
    timeoutMs:integer(configuration,'TIC_REQUEST_TIMEOUT_MS',10_000,1_000,30_000),
  }) : null;
  const resend=configuration.EMAIL_PROVIDER==='resend' ? new ResendEmailProvider({
    apiKey:required(configuration,'RESEND_API_KEY'),webhookSecret:required(configuration,'RESEND_WEBHOOK_SECRET'),
  }) : null;

  const publicSigning: PublicSigningRepository={
    async getInvitation(token){const resolved=await resolveInvitation(database,infrastructure,token);return tenant(database,resolved.tenantId,async tx=>invitationView(tx,resolved));},
    async markOpened(token){const resolved=await resolveInvitation(database,infrastructure,token);await tenant(database,resolved.tenantId,async tx=>{
      const row=await validInvitation(tx,resolved,true);
      await tx.query(`update app.signer_invitations set first_opened_at=coalesce(first_opened_at,now()) where tenant_id=$1 and id=$2`,[resolved.tenantId,resolved.invitationId]);
      await tx.query(`update app.signers set status=case when status='invited' then 'opened'::app.signer_status else status end,status_version=status_version+case when status='invited' then 1 else 0 end where tenant_id=$1 and id=$2`,[resolved.tenantId,row.signer_id]);
      await outbox(tx,resolved.tenantId,'invitation',resolved.invitationId,'invitation.opened',{invitationId:resolved.invitationId,signerId:row.signer_id});
    });return {opened:true};},
    async document(token,documentId){const resolved=await resolveInvitation(database,infrastructure,token);return tenant(database,resolved.tenantId,async tx=>{
      await validInvitation(tx,resolved,false);
      const result=await tx.query<{readonly canonical_object_key:string;readonly display_name:string;readonly sha256:string}>(
        `select v.canonical_object_key,d.display_name,v.sha256 from app.signer_invitations i
          join app.signing_intents si on si.tenant_id=i.tenant_id and si.signer_id=i.signer_id and si.status in ('prepared','provider_started','evidence_collected','verified','packaged')
          join app.signing_intent_documents sid on sid.tenant_id=si.tenant_id and sid.signing_intent_id=si.id
          join app.document_versions v on v.tenant_id=sid.tenant_id and v.id=sid.document_version_id
          join app.documents d on d.tenant_id=v.tenant_id and d.id=v.document_id
         where i.tenant_id=$1 and i.id=$2 and d.id=$3 and v.status in ('locked','partially_signed','signed','validated','archived')
         order by si.created_at desc limit 1`,[resolved.tenantId,resolved.invitationId,documentId]);
      const row=requireRow(result.rows[0],'DOCUMENT_NOT_READY');
      return infrastructure.objectStorage.downloadObject(context(resolved.tenantId),row.canonical_object_key,{contentType:'application/pdf',fileName:row.display_name,sha256:row.sha256});
    });},
    async startBankId(token,input){
      if(!tic)throw new Error('TIC_NOT_CONFIGURED');
      if(input.reviewAcknowledged!==true)throw new Error('DOCUMENT_REVIEW_REQUIRED');
      const resolved=await resolveInvitation(database,infrastructure,token);
      const start=await tenant(database,resolved.tenantId,async tx=>loadStartInput(tx,infrastructure,resolved,input));
      let session;
      try{session=await tic.startSignature(start.providerInput);}catch(error){throw error;}
      const sessionCipher=await infrastructure.sensitiveData.encryptText(JSON.stringify(session),'tic.provider_session');
      const stateCipher=await infrastructure.sensitiveData.encryptText(start.state,'tic.state');
      try{
        await tenant(database,resolved.tenantId,async tx=>{
          const current=await tx.query<{readonly status:string}>(`select status from app.signing_intents where tenant_id=$1 and id=$2 for update`,[resolved.tenantId,start.signingIntentId]);
          if(current.rows[0]?.status!=='prepared')throw new Error('TIC_START_RACE_LOST');
          await tx.query(
            `insert into app.identity_transactions(tenant_id,id,signer_id,document_version_id,signing_intent_id,provider,provider_reference,state_hash,state_ciphertext,nonce_hash,status,started_at,expires_at,provider_session_ciphertext)
             values($1,$2,$3,$4,$5,'TIC_BANKID',$6,$7,$8,$9,'pending',now(),$10,$11)`,
            [resolved.tenantId,start.identityTransactionId,start.signerId,start.firstDocumentVersionId,start.signingIntentId,session.providerReference,await infrastructure.sensitiveData.blindIndex(start.state,'tic.state'),stateCipher,await infrastructure.sensitiveData.blindIndex(start.nonce,'tic.nonce'),session.expiresAt,sessionCipher],
          );
          await tx.query(`update app.signing_intents set status='provider_started',provider_started_at=now() where tenant_id=$1 and id=$2`,[resolved.tenantId,start.signingIntentId]);
          await tx.query(`update app.signers set status='identity_started',status_version=status_version+1 where tenant_id=$1 and id=$2 and status in ('invited','opened')`,[resolved.tenantId,start.signerId]);
          await outbox(tx,resolved.tenantId,'identity_transaction',start.identityTransactionId,'bankid.session_started',{identityTransactionId:start.identityTransactionId,signingIntentId:start.signingIntentId,signerId:start.signerId});
        });
      }catch(error){await tic.cancel(session.providerReference).catch(()=>undefined);throw error;}
      return sessionView(session,false,tic);
    },
    async bankIdStatus(token,sessionId){
      if(!tic)throw new Error('TIC_NOT_CONFIGURED');
      const resolved=await resolveInvitation(database,infrastructure,token);
      const loaded=await tenant(database,resolved.tenantId,async tx=>loadSession(tx,infrastructure,resolved,sessionId));
      const now=Date.now();
      let status=loaded.status;
      if(!loaded.lastPolledAt || now-new Date(loaded.lastPolledAt).getTime()>=1_900){
        status=await tic.getStatus(loaded.providerReference);
        await tenant(database,resolved.tenantId,async tx=>{
          const dbStatus=status==='USER_ACTION_REQUIRED'?'pending':status==='CANCELLED'?'cancelled':status==='EXPIRED'?'expired':status==='FAILED'?'failed':loaded.databaseStatus;
          await tx.query(`update app.identity_transactions set status=$4,last_polled_at=now() where tenant_id=$1 and id=$2 and provider_reference=$3`,[resolved.tenantId,loaded.identityTransactionId,loaded.providerReference,dbStatus]);
          if(status==='COMPLETED'){
            await enqueue(tx,resolved.tenantId,'TIC_EVIDENCE_COLLECT',`tic-collect:${loaded.identityTransactionId}`,{identityTransactionId:loaded.identityTransactionId});
            await outbox(tx,resolved.tenantId,'identity_transaction',loaded.identityTransactionId,'bankid.session_completed',{identityTransactionId:loaded.identityTransactionId});
          }
        });
      }
      return sessionView({...loaded.session,status},loaded.extendedAt!==null,tic,loaded.startedAt);
    },
    async extendBankId(token,sessionId){
      if(!tic)throw new Error('TIC_NOT_CONFIGURED');const resolved=await resolveInvitation(database,infrastructure,token);
      const loaded=await tenant(database,resolved.tenantId,async tx=>loadSession(tx,infrastructure,resolved,sessionId));
      if(loaded.extendedAt)throw new Error('TIC_SESSION_EXTENSION_ALREADY_USED');
      const extended=await tic.extend(sessionId);const cipher=await infrastructure.sensitiveData.encryptText(JSON.stringify(extended),'tic.provider_session');
      await tenant(database,resolved.tenantId,async tx=>{await tx.query(`update app.identity_transactions set extended_at=now(),provider_session_ciphertext=$4 where tenant_id=$1 and id=$2 and provider_reference=$3 and extended_at is null`,[resolved.tenantId,loaded.identityTransactionId,sessionId,cipher]);});
      return sessionView(extended,true,tic,loaded.startedAt);
    },
    async cancelBankId(token,sessionId){if(!tic)throw new Error('TIC_NOT_CONFIGURED');const resolved=await resolveInvitation(database,infrastructure,token);const loaded=await tenant(database,resolved.tenantId,async tx=>loadSession(tx,infrastructure,resolved,sessionId));await tic.cancel(loaded.providerReference);await tenant(database,resolved.tenantId,async tx=>{await tx.query(`update app.identity_transactions set status='cancelled',failure_code='USER_CANCELLED' where tenant_id=$1 and id=$2 and status in ('created','pending')`,[resolved.tenantId,loaded.identityTransactionId]);await tx.query(`update app.signing_intents set status='cancelled' where tenant_id=$1 and id=$2 and status='provider_started'`,[resolved.tenantId,loaded.signingIntentId]);});return {cancelled:true};},
    async decline(token,reason){const resolved=await resolveInvitation(database,infrastructure,token);await tenant(database,resolved.tenantId,async tx=>{const invitation=await validInvitation(tx,resolved,true);const signer=await tx.query<{readonly signature_case_id:string;readonly required:boolean}>(`select signature_case_id,required from app.signers where tenant_id=$1 and id=$2 for update`,[resolved.tenantId,invitation.signer_id]);const row=requireRow(signer.rows[0],'INVITATION_INVALID');await tx.query(`update app.signers set status='declined',status_version=status_version+1 where tenant_id=$1 and id=$2 and status in ('invited','opened','identity_started')`,[resolved.tenantId,invitation.signer_id]);await tx.query(`update app.signer_invitations set used_at=now() where tenant_id=$1 and id=$2`,[resolved.tenantId,resolved.invitationId]);if(row.required)await tx.query(`update app.signature_cases set status='declined',status_version=status_version+1,updated_at=now() where tenant_id=$1 and id=$2 and status in ('sent','in_progress','partially_signed')`,[resolved.tenantId,row.signature_case_id]);await outbox(tx,resolved.tenantId,'signer',invitation.signer_id,'signer.declined',{signerId:invitation.signer_id,signatureCaseId:row.signature_case_id,reasonCode:reason?'RECIPIENT_SUPPLIED':'NOT_SUPPLIED'});});return {declined:true};},
  };

  const providerWebhooks: ProviderWebhookRepository={
    async tic(input){const secret=required(configuration,'TIC_WEBHOOK_SECRET');const signature=input.headers['x-ormeo-signature'];const timestamp=input.headers['x-ormeo-timestamp'];const eventHeader=input.headers['x-ormeo-event'];if(!signature||!timestamp||!eventHeader||!await verifyTicWebhook({rawBody:input.rawBody,signature,timestamp,secret,nowEpochSeconds:Math.floor(new Date(input.receivedAt).getTime()/1000)}))throw new Error('TIC_WEBHOOK_SIGNATURE_INVALID');const envelope=await parseAndHashTicWebhookEnvelope(input.rawBody);if(envelope.event!=='sign.completed'&&eventHeader!=='sign.completed')throw new Error('TIC_WEBHOOK_EVENT_UNSUPPORTED');const global=await database.transaction(async tx=>{const result=await tx.query<{readonly tenant_id:string;readonly identity_transaction_id:string}>(`select * from app.resolve_tic_identity_transaction($1)`,[envelope.sessionId]);return requireRow(result.rows[0],'TIC_WEBHOOK_TRANSACTION_NOT_FOUND');});const duplicate=await tenant(database,global.tenant_id,async tx=>{const identity=await tx.query<{readonly state_ciphertext:Uint8Array}>(`select state_ciphertext from app.identity_transactions where tenant_id=$1 and id=$2`,[global.tenant_id,global.identity_transaction_id]);const state=await infrastructure.sensitiveData.decryptText(requireRow(identity.rows[0],'TIC_WEBHOOK_TRANSACTION_NOT_FOUND').state_ciphertext,'tic.state');assertTicWebhookBinding(envelope,{sessionId:envelope.sessionId,state});const eventId=envelope.eventId??`${envelope.sessionId}:${envelope.event}:${envelope.payloadSha256}`;const inserted=await tx.query(`insert into app.provider_webhook_events(tenant_id,provider,provider_event_id,provider_session_id,event_type,payload_sha256,signature_verified_at) values($1,'tic',$2,$3,$4,$5,now()) on conflict do nothing returning id`,[global.tenant_id,eventId,envelope.sessionId,envelope.event,envelope.payloadSha256]);if(inserted.rowCount===0)return true;await enqueue(tx,global.tenant_id,'TIC_EVIDENCE_COLLECT',`tic-collect:${global.identity_transaction_id}`,{identityTransactionId:global.identity_transaction_id});return false;});return {accepted:true,duplicate};},
    async resend(input){if(!resend)throw new Error('EMAIL_PROVIDER_NOT_CONFIGURED');const event=await resend.verifyWebhook(input);const global=await database.transaction(async tx=>{const result=await tx.query<{readonly tenant_id:string;readonly email_message_id:string}>(`select * from app.resolve_email_message($1,$2)`,['resend',event.providerMessageId]);return requireRow(result.rows[0],'EMAIL_MESSAGE_NOT_FOUND');});const duplicate=await tenant(database,global.tenant_id,async tx=>{const inserted=await tx.query(`insert into app.email_provider_events(tenant_id,email_message_id,provider,provider_event_id,provider_message_id,normalized_status,payload_sha256,occurred_at) values($1,$2,'resend',$3,$4,$5,$6,$7) on conflict do nothing returning id`,[global.tenant_id,global.email_message_id,event.eventId,event.providerMessageId,event.status,event.payloadSha256,event.occurredAt]);if(inserted.rowCount===0)return true;await tx.query(`insert into app.provider_webhook_events(tenant_id,provider,provider_event_id,event_type,payload_sha256,signature_verified_at) values($1,'resend',$2,$3,$4,now()) on conflict do nothing`,[global.tenant_id,event.eventId,event.status,event.payloadSha256]);await tx.query(`update app.email_messages set status=$3,updated_at=now(),delivered_at=case when $3='delivered' then $4 else delivered_at end where tenant_id=$1 and id=$2`,[global.tenant_id,global.email_message_id,event.status,event.occurredAt]);if(event.status==='bounced'||event.status==='complained')await tx.query(`update app.signers s set hard_bounced_at=case when $3='bounced' then $4 else hard_bounced_at end,complained_at=case when $3='complained' then $4 else complained_at end from app.email_messages m where m.tenant_id=s.tenant_id and m.signer_id=s.id and m.tenant_id=$1 and m.id=$2`,[global.tenant_id,global.email_message_id,event.status,event.occurredAt]);return false;});return {accepted:true,duplicate};},
  };

  const publicVerification: PublicVerificationRepository={
    async get(verificationId){if(!/^[A-Za-z0-9_-]{16,100}$/.test(verificationId))return null;const global=await database.transaction(async tx=>{const result=await tx.query<{readonly tenant_id:string;readonly evidence_package_id:string}>(`select * from app.resolve_public_verification($1)`,[verificationId]);return result.rows[0]??null;});if(!global)return null;return tenant(database,global.tenant_id,async tx=>{const packageResult=await tx.query<VerificationRow>(`select ep.package_sha256,ep.ready_at,c.external_reference,c.id as case_id,o.legal_name,(select count(*) from app.signers s where s.tenant_id=c.tenant_id and s.signature_case_id=c.id and s.status='signed') as signer_count,(select max(tia.verified_at) from app.tic_identity_artifacts tia join app.signing_intents si on si.tenant_id=tia.tenant_id and si.id=tia.signing_intent_id where si.tenant_id=c.tenant_id and si.signature_case_id=c.id) as signed_at,(select tia.verifier_engine from app.tic_identity_artifacts tia join app.signing_intents si on si.tenant_id=tia.tenant_id and si.id=tia.signing_intent_id where si.tenant_id=c.tenant_id and si.signature_case_id=c.id order by tia.verified_at desc limit 1) as verifier_engine,(select tia.verifier_policy_version from app.tic_identity_artifacts tia join app.signing_intents si on si.tenant_id=tia.tenant_id and si.id=tia.signing_intent_id where si.tenant_id=c.tenant_id and si.signature_case_id=c.id order by tia.verified_at desc limit 1) as verifier_policy_version from app.evidence_packages ep join app.signature_cases c on c.tenant_id=ep.tenant_id and c.id=ep.signature_case_id left join app.organizations o on o.tenant_id=c.tenant_id where ep.tenant_id=$1 and ep.id=$2 limit 1`,[global.tenant_id,global.evidence_package_id]);const row=requireRow(packageResult.rows[0],'NOT_FOUND');const docs=await tx.query<{readonly display_name:string;readonly sha256:string}>(`select distinct d.display_name,v.sha256 from app.documents d join app.document_versions v on v.tenant_id=d.tenant_id and v.document_id=d.id where d.tenant_id=$1 and d.signature_case_id=$2 order by d.display_name`,[global.tenant_id,row.case_id]);return {verified:true,organization:row.legal_name??'Kommunsign-tenant',caseReference:row.external_reference??row.case_id,documents:docs.rows.map(d=>({displayName:d.display_name,sha256:d.sha256})),signerCount:Number(row.signer_count),signedAt:new Date(row.signed_at).toISOString(),verifierEngine:row.verifier_engine,verifierPolicyVersion:row.verifier_policy_version,packageSha256:row.package_sha256};});},
    async verifyPackage(bytes){return verifyEvidenceZip(bytes);},
  };
  void createEvidenceZip;
  return {publicSigning,providerWebhooks,publicVerification};
}

interface InvitationResolution{readonly tenantId:string;readonly invitationId:string;readonly signerId:string;readonly tokenHash:Uint8Array;}
async function resolveInvitation(database:SqlDatabase,infrastructure:ProductionInfrastructure,token:string):Promise<InvitationResolution>{if(!isSafeOpaqueToken(token))throw new Error('INVITATION_INVALID');const tokenHash=await infrastructure.sensitiveData.blindIndex(token,'signer.invitation_token');return database.transaction(async tx=>{const result=await tx.query<{readonly tenant_id:string;readonly invitation_id:string;readonly signer_id:string}>(`select * from app.resolve_public_invitation($1)`,[tokenHash]);const row=requireRow(result.rows[0],'INVITATION_INVALID');return{tenantId:row.tenant_id,invitationId:row.invitation_id,signerId:row.signer_id,tokenHash};});}
async function validInvitation(tx:SqlTransaction,resolved:InvitationResolution,lock:boolean){const result=await tx.query<{readonly signer_id:string;readonly expires_at:string|Date;readonly revoked_at:string|null;readonly used_at:string|null}>(`select signer_id,expires_at,revoked_at,used_at from app.signer_invitations where tenant_id=$1 and id=$2 ${lock?'for update':''}`,[resolved.tenantId,resolved.invitationId]);const row=requireRow(result.rows[0],'INVITATION_INVALID');if(row.revoked_at||row.used_at)throw new Error('INVITATION_REVOKED');if(new Date(row.expires_at).getTime()<=Date.now())throw new Error('INVITATION_EXPIRED');return row;}
async function invitationView(tx:SqlTransaction,resolved:InvitationResolution):Promise<PublicSigningInvitationView>{const result=await tx.query<InvitationViewRow>(`select i.id as invitation_id,i.expires_at,s.id as signer_id,s.signature_case_id,s.display_name,s.status::text as signer_status,s.identifier_binding_mode,c.title,c.external_reference,coalesce(o.legal_name,'Kommunsign-tenant') as organization_name,si.visible_text from app.signer_invitations i join app.signers s on s.tenant_id=i.tenant_id and s.id=i.signer_id join app.signature_cases c on c.tenant_id=s.tenant_id and c.id=s.signature_case_id left join app.organizations o on o.tenant_id=c.tenant_id join app.signing_intents si on si.tenant_id=s.tenant_id and si.signer_id=s.id where i.tenant_id=$1 and i.id=$2 and i.revoked_at is null and i.used_at is null and i.expires_at>now() and si.status in ('prepared','provider_started','evidence_collected','verified','packaged') order by si.created_at desc limit 1`,[resolved.tenantId,resolved.invitationId]);const row=requireRow(result.rows[0],'INVITATION_INVALID');const docs=await tx.query<{readonly document_id:string;readonly display_name_snapshot:string;readonly document_sha256:string;readonly byte_size_snapshot:number|string;readonly ordinal:number}>(`select d.id as document_id,sid.display_name_snapshot,sid.document_sha256,sid.byte_size_snapshot,sid.ordinal from app.signing_intents si join app.signing_intent_documents sid on sid.tenant_id=si.tenant_id and sid.signing_intent_id=si.id join app.document_versions v on v.tenant_id=sid.tenant_id and v.id=sid.document_version_id join app.documents d on d.tenant_id=v.tenant_id and d.id=v.document_id where si.tenant_id=$1 and si.signer_id=$2 and si.status in ('prepared','provider_started','evidence_collected','verified','packaged') order by si.created_at desc,sid.ordinal`,[resolved.tenantId,row.signer_id]);return{invitationId:row.invitation_id,signerId:row.signer_id,signatureCaseId:row.signature_case_id,organizationName:row.organization_name,caseReference:row.external_reference??row.signature_case_id,caseTitle:row.title,signerDisplayName:row.display_name,status:row.signer_status,expiresAt:new Date(row.expires_at).toISOString(),identifierBindingMode:row.identifier_binding_mode,visibleText:row.visible_text,documents:docs.rows.map(d=>({id:d.document_id,displayName:d.display_name_snapshot,sha256:d.document_sha256,byteSize:Number(d.byte_size_snapshot),mimeType:'application/pdf',profile:'PDF/A-2b',ordinal:d.ordinal}))};}
async function loadStartInput(tx:SqlTransaction,infrastructure:ProductionInfrastructure,resolved:InvitationResolution,input:{readonly endUserIp:string;readonly userAgent:string}){await validInvitation(tx,resolved,true);const rollout=await tx.query<{readonly tic_bankid_rollout_enabled:boolean}>(`select tic_bankid_rollout_enabled from app.tenant_signing_settings where tenant_id=$1`,[resolved.tenantId]);if(!rollout.rows[0]?.tic_bankid_rollout_enabled)throw new Error('TIC_NOT_CONFIGURED');const blocked=await tx.query(`select 1 from app.signers target where target.tenant_id=$1 and target.id=$2 and exists(select 1 from app.signers lower where lower.tenant_id=target.tenant_id and lower.signature_case_id=target.signature_case_id and lower.signing_order<target.signing_order and lower.required and lower.status<>'signed')`,[resolved.tenantId,resolved.signerId]);if(blocked.rowCount)throw new Error('SIGNING_ORDER_BLOCKED');const result=await tx.query<StartRow>(`select si.id as signing_intent_id,si.signature_case_id,si.signer_id,si.visible_text,si.non_visible_payload,si.issued_at,si.expires_at,c.policy_id,c.policy_version,s.identifier_binding_mode,s.expected_identifier_ciphertext,(select sid.document_version_id from app.signing_intent_documents sid where sid.tenant_id=si.tenant_id and sid.signing_intent_id=si.id order by sid.ordinal limit 1) as first_document_version_id from app.signing_intents si join app.signature_cases c on c.tenant_id=si.tenant_id and c.id=si.signature_case_id join app.signers s on s.tenant_id=si.tenant_id and s.id=si.signer_id where si.tenant_id=$1 and si.signer_id=$2 and si.status='prepared' order by si.created_at desc limit 1 for update`,[resolved.tenantId,resolved.signerId]);const row=requireRow(result.rows[0],'SIGNING_INTENT_NOT_READY');const payload=JSON.parse(row.non_visible_payload) as {readonly nonce:string;readonly documents:readonly any[]};const expected=row.identifier_binding_mode==='STRICT_PREBOUND'?await infrastructure.sensitiveData.decryptText(requireRowValue(row.expected_identifier_ciphertext,'PERSONAL_NUMBER_REQUIRED'),'signer.expected_personal_number'):undefined;const state=randomToken(32);const identityTransactionId=crypto.randomUUID();return{identityTransactionId,signingIntentId:row.signing_intent_id,signerId:row.signer_id,firstDocumentVersionId:row.first_document_version_id,state,nonce:payload.nonce,providerInput:{tenantId:resolved.tenantId,signatureCaseId:row.signature_case_id,signingIntentId:row.signing_intent_id,signerId:row.signer_id,signaturePolicyId:row.policy_id,signaturePolicyVersion:row.policy_version,identifierBindingMode:row.identifier_binding_mode,...(expected?{expectedPersonalNumber:expected}:{}),documents:payload.documents,visibleText:row.visible_text,endUserIp:input.endUserIp,userAgent:input.userAgent,issuedAt:new Date(row.issued_at).toISOString(),expiresAt:new Date(row.expires_at).toISOString(),state,nonce:payload.nonce}};}
async function loadSession(tx:SqlTransaction,infrastructure:ProductionInfrastructure,resolved:InvitationResolution,sessionId:string){await validInvitation(tx,resolved,false);const result=await tx.query<SessionRow>(`select it.id,it.provider_reference,it.provider_session_ciphertext,it.status,it.started_at,it.expires_at,it.last_polled_at,it.extended_at,it.signing_intent_id from app.identity_transactions it join app.signers s on s.tenant_id=it.tenant_id and s.id=it.signer_id where it.tenant_id=$1 and s.id=$2 and it.provider_reference=$3`,[resolved.tenantId,resolved.signerId,sessionId]);const row=requireRow(result.rows[0],'TIC_SESSION_NOT_FOUND');const session=JSON.parse(await infrastructure.sensitiveData.decryptText(row.provider_session_ciphertext,'tic.provider_session'));return{identityTransactionId:row.id,providerReference:row.provider_reference,session,databaseStatus:row.status,status:row.status,lastPolledAt:row.last_polled_at?new Date(row.last_polled_at).toISOString():null,extendedAt:row.extended_at?new Date(row.extended_at).toISOString():null,startedAt:new Date(row.started_at).toISOString(),signingIntentId:row.signing_intent_id};}
async function sessionView(session:any,extended:boolean,tic:TicBankIdProvider,startedAt?:string):Promise<PublicBankIdSessionView>{const elapsed=Math.max(0,Math.floor((Date.now()-new Date(startedAt??new Date().toISOString()).getTime())/1000));const qr=session.qrStartToken&&session.qrStartSecret?await tic.createQrCodeData(session.qrStartToken,session.qrStartSecret,elapsed):undefined;return{sessionId:session.providerReference??session.id,status:session.status,expiresAt:session.expiresAt,...(session.autoStartToken?{autoStartToken:session.autoStartToken}:{}),...(qr?{qrCodeData:qr}:{}),canExtend:!extended};}
async function tenant<T>(database:SqlDatabase,tenantId:string,work:(tx:SqlTransaction)=>Promise<T>):Promise<T>{return withTenantTransaction(database,context(tenantId),'trusted_service',work);}
function context(tenantId:string):TenantContext{return{tenantId,subjectId:SYSTEM_ACTOR_ID,requestId:crypto.randomUUID(),authMethod:'trusted_service',source:'deployment'};}
async function outbox(tx:SqlTransaction,tenantId:string,aggregateType:string,aggregateId:string,eventType:string,payload:Readonly<Record<string,unknown>>){const json=JSON.stringify(payload);await tx.query(`insert into app.outbox_events(tenant_id,aggregate_type,aggregate_id,event_type,payload,payload_sha256) values($1,$2,$3,$4,$5::jsonb,$6)`,[tenantId,aggregateType,aggregateId,eventType,json,await sha256Hex(json)]);}
async function enqueue(tx:SqlTransaction,tenantId:string,type:string,key:string,payload:Readonly<Record<string,unknown>>){await tx.query(`insert into app.durable_jobs(tenant_id,job_type,payload,idempotency_key,status,available_at,maximum_attempts) values($1,$2,$3::jsonb,$4,'pending',now(),10) on conflict(tenant_id,job_type,idempotency_key) do nothing`,[tenantId,type,JSON.stringify(payload),key]);}
function required(env:Readonly<Record<string,string|undefined>>,name:string){const value=env[name]?.trim();if(!value)throw new Error(`${name}_MISSING`);return value;}
function integer(env:Readonly<Record<string,string|undefined>>,name:string,fallback:number,min:number,max:number){const n=Number(env[name]??fallback);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`${name}_INVALID`);return n;}
function requireRow<T>(row:T|undefined,code:string):T{if(!row)throw new Error(code);return row;}
function requireRowValue<T>(value:T|null|undefined,code:string):T{if(value===null||value===undefined)throw new Error(code);return value;}
interface InvitationViewRow{readonly invitation_id:string;readonly expires_at:string|Date;readonly signer_id:string;readonly signature_case_id:string;readonly display_name:string;readonly signer_status:any;readonly identifier_binding_mode:'STRICT_PREBOUND'|'BANKID_DISCOVERED';readonly title:string;readonly external_reference:string|null;readonly organization_name:string;readonly visible_text:string;}
interface StartRow{readonly signing_intent_id:string;readonly signature_case_id:string;readonly signer_id:string;readonly visible_text:string;readonly non_visible_payload:string;readonly issued_at:string|Date;readonly expires_at:string|Date;readonly policy_id:string;readonly policy_version:number;readonly identifier_binding_mode:'STRICT_PREBOUND'|'BANKID_DISCOVERED';readonly expected_identifier_ciphertext:Uint8Array|null;readonly first_document_version_id:string;}
interface SessionRow{readonly id:string;readonly provider_reference:string;readonly provider_session_ciphertext:Uint8Array;readonly status:any;readonly started_at:string|Date;readonly expires_at:string|Date;readonly last_polled_at:string|Date|null;readonly extended_at:string|Date|null;readonly signing_intent_id:string;}
interface VerificationRow{readonly package_sha256:string;readonly ready_at:string|Date;readonly external_reference:string|null;readonly case_id:string;readonly legal_name:string|null;readonly signer_count:number|string;readonly signed_at:string|Date;readonly verifier_engine:string;readonly verifier_policy_version:string;}
